version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=psw@123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5437:5432'
volumes:
  postgres: